spring:
  application:
    name: holodos-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/holodos
    username: holodos
    password: holodos
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=10m

server:
  error:
    include-message: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
