CREATE TABLE stock_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products (id),
    quantity NUMERIC(14, 3) NOT NULL,
    unit_id BIGINT NOT NULL REFERENCES units (id),
    storage_place_id BIGINT NOT NULL REFERENCES storage_places (id),
    added_at TIMESTAMPTZ NOT NULL,
    purchased_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    opened_at TIMESTAMPTZ,
    comment VARCHAR(1000),
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_stock_entries_product_status ON stock_entries (product_id, status);
CREATE INDEX idx_stock_entries_expires_at ON stock_entries (expires_at);

CREATE TABLE inventory_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products (id),
    stock_entry_id BIGINT NOT NULL REFERENCES stock_entries (id),
    from_storage_place_id BIGINT NOT NULL REFERENCES storage_places (id),
    to_storage_place_id BIGINT NOT NULL REFERENCES storage_places (id),
    quantity NUMERIC(14, 3) NOT NULL,
    moved_at TIMESTAMPTZ NOT NULL,
    comment VARCHAR(1000),
    username VARCHAR(120) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE shopping_list_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products (id),
    title VARCHAR(200) NOT NULL,
    quantity NUMERIC(14, 3) NOT NULL,
    unit_id BIGINT REFERENCES units (id),
    store_id BIGINT REFERENCES stores (id),
    status VARCHAR(32) NOT NULL,
    source VARCHAR(32) NOT NULL,
    comment VARCHAR(1000),
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_shopping_product_status ON shopping_list_items (product_id, status);

CREATE TABLE purchase_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shopping_list_item_id BIGINT REFERENCES shopping_list_items (id),
    product_id BIGINT NOT NULL REFERENCES products (id),
    quantity NUMERIC(14, 3) NOT NULL,
    unit_id BIGINT NOT NULL REFERENCES units (id),
    store_id BIGINT REFERENCES stores (id),
    purchased_at TIMESTAMPTZ NOT NULL,
    storage_place_id BIGINT NOT NULL REFERENCES storage_places (id),
    expires_at TIMESTAMPTZ,
    comment VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
