CREATE TABLE user_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_key VARCHAR(120) NOT NULL UNIQUE,
    expiry_days_before_notify INT NOT NULL DEFAULT 3,
    notify_expiring BOOLEAN NOT NULL DEFAULT TRUE,
    notify_expired BOOLEAN NOT NULL DEFAULT TRUE,
    notify_old_items BOOLEAN NOT NULL DEFAULT TRUE,
    notify_out_of_stock BOOLEAN NOT NULL DEFAULT TRUE,
    quiet_hours_start VARCHAR(5),
    quiet_hours_end VARCHAR(5),
    max_frequency_minutes INT NOT NULL DEFAULT 360,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(64) NOT NULL,
    title VARCHAR(200) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    entity_type VARCHAR(120),
    entity_id VARCHAR(120),
    dedup_key VARCHAR(200),
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    delivered_at TIMESTAMPTZ,
    read_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX ux_notifications_dedup_key ON notifications (dedup_key) WHERE dedup_key IS NOT NULL;

CREATE TABLE sync_bindings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_key VARCHAR(120) NOT NULL,
    provider VARCHAR(64) NOT NULL,
    remote_note_id VARCHAR(200) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_synced_at TIMESTAMPTZ,
    last_remote_etag VARCHAR(200),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ux_sync_binding UNIQUE (user_key, provider)
);

CREATE TABLE sync_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    binding_id BIGINT NOT NULL REFERENCES sync_bindings (id),
    event_type VARCHAR(64) NOT NULL,
    direction VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL,
    correlation_id VARCHAR(64),
    details VARCHAR(2000),
    idempotency_key VARCHAR(200),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
