CREATE TABLE inventory_adjustments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_entry_id BIGINT NOT NULL REFERENCES stock_entries (id),
    product_id BIGINT NOT NULL REFERENCES products (id),
    delta NUMERIC(14, 3) NOT NULL,
    reason VARCHAR(64) NOT NULL,
    comment VARCHAR(1000),
    username VARCHAR(120) NOT NULL,
    adjusted_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_inventory_adjustments_entry ON inventory_adjustments (stock_entry_id);
