name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2222
          script: |
            export PATH=$PATH:/snap/bin
            cd /home/slavco/holodos
            git pull https://${{ secrets.GH_PAT }}@github.com/zavgorodniyvv/holodos.git
            docker compose build --no-cache
            docker compose up -d
